name: KillMobMoney
main: KillMobMoney\KillMobMoney
version: 1.0.0
api: [3.11.5, 3.11.6]
depend: [EconomyAPI]
softDepend: [PureEntitiesX]

author: peptiGamer
description: A PocketMine-MP plugin killing Mobs give Money
permissions:
 killmobmoney:
  description: Permission to earn money by killing other players.
  default: true
